### PR TITLE
improve wind speed measurement

### PR DESCRIPTION
**Pull request by takluyver**
Making a pull request so that this doesn't get overlooked. @Nanoseb is there anything more you want to do or check on this before merging it?

See issues #44 #46

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Maritime-Robotics-Student-Society/sailing-robot/pull/49" target="_blank">ReviewNinja

**Comment by Nanoseb** [comment]
If someone can try to compile it it can be useful to spot typos (I can't do that on my laptop), for the code itself it should work fine because it contains only minor changes from the previous version.

**Comment by tsaoyu** [comment]
Successfully compiled with Arduino IDE (version 1.6.3) @Nanoseb

**Comment by Nanoseb** [comment]
ok great, so I think you can merge.

**Pull request merged**
