### PR TITLE
Dashboard prototype

### PR DESCRIPTION
**Pull request by takluyver**
This is a very quick prototype of an idea I've had for #65. It opens up a lot more possibilities for better monitoring, but I think it will be useful already even in its present form.

The idea is to run a web server as a ROS node, and serve a live-updating HTML dashboard. Then anyone connected to the raspi wifi can monitor it in a browser by going to `(raspi ip address):8448`. There's no need to configure ROS for the network, or even install ROS on the computer you're monitoring from. With a bit of careful design, it should even be possible to monitor it from a phone.

Here it is running a dummy launch file on the VM - I was in the midst of changing how some other stuff works, so there weren't many topics available to view, but it should give the idea:

dashboard-screenshot

If ROS goes down or it loses the connection, it makes it clear that the dashboard is no longer live:

disconnected screenshot

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/Maritime-Robotics-Student-Society/sailing-robot/pull/68" target="_blank">ReviewNinja

**Comment by tsaoyu** [comment]
I do like this idea 🆒 

Worth a try on our RPi.

**Comment by tsaoyu** [comment]
I couldn't find `Navigation` package in our current repo. 
Is that new package create by you?

**Comment by takluyver** [comment]
Yes, sorry - `Navigation` is in the [tasks branch](https://github.com/takluyver/sailing-robot/tree/tasks) of my fork. I haven't made a pull request for that yet because it's a work in progress.

This doesn't actually use the Navigation object, however. I'd put that in place for future plans like distances in metres. I'll update the code not to import it soon.

**Pull request merged**
